on: workflow_dispatch

name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends ffmpeg
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: video.mp4
          path: out/video.mp4
