on: workflow_dispatch

name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt-get update
      - run: sudo apt-get install --no-install-recommends ffmpeg
      - run: |
          sudo apt-get install --no-install-recommends  \
            libnss3 \
            libdbus-1-3 \
            libatk1.0-0 \
            libasound2t64 \
            libxrandr2 \
            libxkbcommon-dev \
            libxfixes3 \
            libxcomposite1 \
            libxdamage1 \
            libgbm-dev \
            libcups2 \
            libcairo2 \
            libpango-1.0-0 \
            libatk-bridge2.0-0
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@main
        with:
          name: gigachad.gif
          path: out/gigachad.gif
